services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GENIUS_TOKEN=${GENIUS_TOKEN}
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
