// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SearchHit {
    title: string;
    artist: string;
    id: number;
    thumbnail: string;
    url: string;
}
